### ISSUE TITLE
Getting Specific Text from PDF file

### ISSUE THREAD

**Issue by kunallibra** [asika32764/php-pdf-2-text#5]
I am able to decode the PDF in text format. Actually, I wanted to get a specific values from the PDF file is it possible?

The values that I need from the PDF is the ID, PurchaseOrderID, SupplierID and Amount. I need this four values from the PDF files and then I want to use it further.

Can you suggest me something please?

Thanks

**Comment by asika32764** [comment]
Unfortunately this library unable to parse PDF raw content, it just get the raw text.

You must find other tools to help you.

Good luck.
